/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.GdcbFuncionario;
import dao.gdcb_funcionarioDAO;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tools.Util;

/**
 *
 * @author Acer
 */
public class JDlgFuncionarios extends javax.swing.JDialog {

    private boolean incluir;

    /**
     * Creates new form JDlgFuncionarios
     */
    public JDlgFuncionarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("gdcb_funcionarios");
        setLocationRelativeTo(null);
        Util.habilitar(false, jFmtIdfuncionario, JtxtNome, JtxtEmail,
                jFmtCPF, jFmtDataNascimento, jChbCLT, jCboCargo,
                jChbAtivo, jBtnConfirmar, jBtnCancelar, jChbAtivoF);
    }

    public void beanView(GdcbFuncionario funcionarios) {
        jFmtIdfuncionario.setText(Util.intToStr(funcionarios.getGdcbIdfuncionario()));
        JtxtNome.setText(funcionarios.getGdcbNomeFuncionario());
        JtxtEmail.setText(funcionarios.getGdcbEmailFuncionario());

        String cpf = funcionarios.getGdcbCpfFuncionario();
        if (cpf != null && !cpf.isEmpty()) {
            cpf = cpf.replaceAll("[^0-9]", "");
            if (cpf.length() == 11) {
                jFmtCPF.setText(cpf.substring(0, 3) + "." + cpf.substring(3, 6) + "."
                        + cpf.substring(6, 9) + "-" + cpf.substring(9));
            } else {
                jFmtCPF.setText(cpf);
            }
        } else {
            jFmtCPF.setText("");
        }

        jFmtDataNascimento.setText(Util.dateToStr(funcionarios.getGdcbDataNascimentoFuncionario()));
        jCboCargo.setSelectedItem(funcionarios.getGdcbCargo());

        if (funcionarios.getGdcbClt().equals("S")) {
            jChbCLT.setSelected(true);
        } else {
            jChbCLT.setSelected(false);
        }

        if (funcionarios.getGdcbAtivo().equals("S")) {
            jChbAtivoF.setSelected(true);
        } else {
            jChbAtivoF.setSelected(false);
        }
    }

    public GdcbFuncionario viewBean() throws ParseException {
        GdcbFuncionario funcionarios = new GdcbFuncionario();

        int codigo = Util.strToInt(jFmtIdfuncionario.getText());
        funcionarios.setGdcbIdfuncionario(codigo);

        funcionarios.setGdcbNomeFuncionario(JtxtNome.getText());
        funcionarios.setGdcbEmailFuncionario(JtxtEmail.getText());

        String cpf = jFmtCPF.getText().replaceAll("[^0-9]", "");
        if (cpf.length() != 11) {
            Util.mensagem("CPF inválido! Deve conter 11 dígitos.");
            jFmtCPF.requestFocus();
            return null;
        }

        if (cpf.matches("(\\d)\\1{10}")) {
            Util.mensagem("CPF inválido! Não pode ter todos os dígitos iguais.");
            jFmtCPF.requestFocus();
            return null;
        }

        int soma = 0;
        for (int i = 0; i < 9; i++) {
            soma += Character.getNumericValue(cpf.charAt(i)) * (10 - i);
        }
        int resto = soma % 11;
        int digito1 = (resto < 2) ? 0 : 11 - resto;

        if (Character.getNumericValue(cpf.charAt(9)) != digito1) {
            Util.mensagem("CPF inválido! Dígito verificador incorreto.");
            jFmtCPF.requestFocus();
            return null;
        }

        soma = 0;
        for (int i = 0; i < 10; i++) {
            soma += Character.getNumericValue(cpf.charAt(i)) * (11 - i);
        }
        resto = soma % 11;
        int digito2 = (resto < 2) ? 0 : 11 - resto;

        if (Character.getNumericValue(cpf.charAt(10)) != digito2) {
            Util.mensagem("CPF inválido! Dígito verificador incorreto.");
            jFmtCPF.requestFocus();
            return null;
        }

        funcionarios.setGdcbCpfFuncionario(cpf);

        funcionarios.setGdcbDataNascimentoFuncionario(Util.strToDate(jFmtDataNascimento.getText()));
        funcionarios.setGdcbCargo(jCboCargo.getSelectedItem().toString());

        if (jChbCLT.isSelected()) {
            funcionarios.setGdcbClt("S");
        } else {
            funcionarios.setGdcbClt("N");
        }

        if (jChbAtivoF.isSelected()) {
            funcionarios.setGdcbAtivo("S");
        } else {
            funcionarios.setGdcbAtivo("N");
        }

        return funcionarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jChbAtivo = new javax.swing.JCheckBox();
        JlbCurso = new javax.swing.JLabel();
        jCboCurso = new javax.swing.JComboBox<>();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        JlbEmail = new javax.swing.JLabel();
        JtxtEmail = new javax.swing.JTextField();
        JlbNome = new javax.swing.JLabel();
        JtxtNome = new javax.swing.JTextField();
        jChbAtivoF = new javax.swing.JCheckBox();
        JlbCargo = new javax.swing.JLabel();
        jCboCargo = new javax.swing.JComboBox<>();
        jChbCLT = new javax.swing.JCheckBox();
        JlbCPF = new javax.swing.JLabel();
        jFmtCPF = new javax.swing.JFormattedTextField();
        JlbDataNascimento = new javax.swing.JLabel();
        jFmtDataNascimento = new javax.swing.JFormattedTextField();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        JbtnExcluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        JlbId = new javax.swing.JLabel();
        jFmtIdfuncionario = new javax.swing.JFormattedTextField();
        jBtnIncluir = new javax.swing.JButton();

        jChbAtivo.setText("Ativo");
        jChbAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbAtivoActionPerformed(evt);
            }
        });

        JlbCurso.setText("Curso Atual");

        jCboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JlbEmail.setText("E-mail");

        JtxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtEmailActionPerformed(evt);
            }
        });

        JlbNome.setText("Nome Funcionário");

        JtxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtNomeActionPerformed(evt);
            }
        });

        jChbAtivoF.setText("Ativo");
        jChbAtivoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbAtivoFActionPerformed(evt);
            }
        });

        JlbCargo.setText("Cargo");

        jCboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CEO", "Caixa", "Ajuda ao Cliente ", "Higiene ", "Segurança ", "Divulgador Literário" }));

        jChbCLT.setText("CLT");
        jChbCLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbCLTActionPerformed(evt);
            }
        });

        JlbCPF.setText("CPF Funcionário");

        JlbDataNascimento.setText("Data de Nascimento");

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        JbtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Excluir.png"))); // NOI18N
        JbtnExcluir.setText("Excluir");
        JbtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnExcluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/ok.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        JlbId.setText("ID ");

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlbEmail)
                        .addGap(18, 18, 18)
                        .addComponent(JtxtEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlbCPF)
                        .addGap(12, 12, 12)
                        .addComponent(jFmtCPF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlbDataNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFmtDataNascimento))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JlbNome)
                            .addComponent(JlbId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JtxtNome)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jFmtIdfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JlbCargo)
                                .addGap(18, 18, 18)
                                .addComponent(jCboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jChbAtivoF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jChbCLT))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JbtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnPesquisar))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlbId)
                    .addComponent(jFmtIdfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlbNome)
                    .addComponent(JtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlbCPF)
                    .addComponent(jFmtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlbDataNascimento)
                    .addComponent(jFmtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlbEmail)
                    .addComponent(JtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlbCargo)
                    .addComponent(jCboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbAtivoF)
                    .addComponent(jChbCLT))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnExcluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnIncluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtEmailActionPerformed

    private void JtxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtNomeActionPerformed

    private void jChbAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbAtivoActionPerformed

    private void jChbAtivoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbAtivoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbAtivoFActionPerformed

    private void jChbCLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbCLTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbCLTActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        Util.habilitar(false, jFmtIdfuncionario, JtxtNome, JtxtEmail,
                jFmtCPF, jFmtDataNascimento, jChbCLT, jCboCargo,
                jChbAtivo, jBtnConfirmar, jBtnCancelar, jChbAtivoF);

        Util.habilitar(true, jBtnIncluir, jBtnAlterar, JbtnExcluir, jBtnPesquisar);
        Util.limpar(jFmtIdfuncionario, JtxtNome, JtxtEmail,
                jFmtCPF, jFmtDataNascimento, jChbCLT, jCboCargo,
                jChbAtivo, jBtnConfirmar, jBtnCancelar, jChbAtivoF); // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        JDlgFuncionariosPesquisar jDlgFuncionariosPesquisar = new JDlgFuncionariosPesquisar(null, true);
        jDlgFuncionariosPesquisar.setTelaAnterior(this);
        jDlgFuncionariosPesquisar.setVisible(true);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void JbtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnExcluirActionPerformed
        if (Util.pergunta("Deseja excluir ?") == true) {
            gdcb_funcionarioDAO gdcb_funcionarioDAO = new gdcb_funcionarioDAO();
            try {
                gdcb_funcionarioDAO.delete(viewBean());
                Util.limpar(jFmtIdfuncionario, JtxtNome, JtxtEmail,
                        jFmtCPF, jFmtDataNascimento, jChbCLT, jCboCargo,
                        jChbAtivo, jBtnConfirmar, jBtnCancelar, jChbAtivoF);
            } catch (ParseException ex) {
                Logger.getLogger(JDlgFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_JbtnExcluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        Util.habilitar(true, jFmtIdfuncionario, JtxtNome, JtxtEmail,
                jFmtCPF, jFmtDataNascimento, jChbCLT, jCboCargo,
                jChbAtivo, jBtnConfirmar, jBtnCancelar, jChbAtivoF);

        Util.habilitar(false, jBtnIncluir, jBtnAlterar, JbtnExcluir, jBtnPesquisar);

        incluir = false;

    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed

        gdcb_funcionarioDAO gdcb_funcionarioDAO = new gdcb_funcionarioDAO();
        GdcbFuncionario gdcb_funcionario = null;
        try {
            gdcb_funcionario = viewBean();
        } catch (ParseException ex) {
            Logger.getLogger(JDlgFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (incluir == true) {
            gdcb_funcionarioDAO.insert(gdcb_funcionario);

        } else {
            gdcb_funcionarioDAO.update(gdcb_funcionario);

        }
        Util.habilitar(false, jFmtIdfuncionario, JtxtNome, JtxtEmail,
                jFmtCPF, jFmtDataNascimento, jChbCLT, jCboCargo,
                jChbAtivo, jBtnConfirmar, jBtnCancelar, jChbAtivoF);

        Util.habilitar(true, jBtnIncluir, jBtnAlterar, JbtnExcluir, jBtnPesquisar);
        Util.limpar(jFmtIdfuncionario, JtxtNome, JtxtEmail,
                jFmtCPF, jFmtDataNascimento, jChbCLT, jCboCargo,
                jChbAtivo, jBtnConfirmar, jBtnCancelar, jChbAtivoF);

    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        Util.habilitar(true, jFmtIdfuncionario, JtxtNome, JtxtEmail,
                jFmtCPF, jFmtDataNascimento, jChbCLT, jCboCargo,
                jChbAtivo, jBtnConfirmar, jBtnCancelar, jChbAtivoF);

        Util.habilitar(false, jBtnIncluir, jBtnAlterar, JbtnExcluir, jBtnPesquisar);
        Util.limpar(jFmtIdfuncionario, JtxtNome, JtxtEmail,
                jFmtCPF, jFmtDataNascimento, jChbCLT, jCboCargo,
                jChbAtivo, jBtnConfirmar, jBtnCancelar, jChbAtivoF);
        incluir = true;
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgFuncionarios dialog = new JDlgFuncionarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnExcluir;
    private javax.swing.JLabel JlbCPF;
    private javax.swing.JLabel JlbCargo;
    private javax.swing.JLabel JlbCurso;
    private javax.swing.JLabel JlbDataNascimento;
    private javax.swing.JLabel JlbEmail;
    private javax.swing.JLabel JlbId;
    private javax.swing.JLabel JlbNome;
    private javax.swing.JTextField JtxtEmail;
    private javax.swing.JTextField JtxtNome;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCboCargo;
    private javax.swing.JComboBox<String> jCboCurso;
    private javax.swing.JCheckBox jChbAtivo;
    private javax.swing.JCheckBox jChbAtivoF;
    private javax.swing.JCheckBox jChbCLT;
    private javax.swing.JFormattedTextField jFmtCPF;
    private javax.swing.JFormattedTextField jFmtDataNascimento;
    private javax.swing.JFormattedTextField jFmtIdfuncionario;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    // End of variables declaration//GEN-END:variables
}
