package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Acer
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    public JFrmPrincipal() {
        initComponents();
        try {
            final Image img = new ImageIcon(getClass().getResource("/imagem/P-1.png")).getImage();
            setContentPane(new javax.swing.JPanel() {
                @Override
                protected void paintComponent(Graphics g) {
                    super.paintComponent(g);
                    g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
                }
            });

            getContentPane().add(jToolBar2);

        } catch (Exception e) {
        }

        JDlgLogin telaLogin = new JDlgLogin(this, true);
        telaLogin.setVisible(true);

        if (!telaLogin.isLoginSucedido()) {
            System.exit(0);
            return;
        }
        setTitle("SistemaGiovannaBernazzolli");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar2 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jMnuClientes = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMnuProdutos = new javax.swing.JMenuItem();
        jMnuSair1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnuUsuarios1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMnuUsuarios2 = new javax.swing.JMenuItem();
        jMnuUsuarios3 = new javax.swing.JMenuItem();
        jMnuUsuarios4 = new javax.swing.JMenuItem();
        jMnuUsuarios5 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar2.setRollover(true);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/nuit.png"))); // NOI18N
        jButton4.setText(" Produto");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/sorciere.png"))); // NOI18N
        jButton5.setText("Usuário");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/role-playing.png"))); // NOI18N
        jButton6.setText("Clientes");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cat-sleep.png"))); // NOI18N
        jButton7.setText("Consulta Usuário");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/dragon.png"))); // NOI18N
        jButton8.setText("Consulta Produto");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton8);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cadastro.JPG"))); // NOI18N
        jMenu1.setMnemonic('C');
        jMenu1.setText("Cadastros");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fadaIcon.png"))); // NOI18N
        jMnuUsuarios.setMnemonic('u');
        jMnuUsuarios.setText("Usuários");
        jMnuUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosActionPerformed(evt);
            }
        });
        jMnuUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMnuUsuariosKeyPressed(evt);
            }
        });
        jMenu1.add(jMnuUsuarios);

        jMnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/clientes.JPG"))); // NOI18N
        jMnuClientes.setMnemonic('c');
        jMnuClientes.setText("Clientes");
        jMnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuClientes);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/funcionario.JPG"))); // NOI18N
        jMenuItem2.setMnemonic('f');
        jMenuItem2.setText("Funcionários");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMnuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/produto.JPG"))); // NOI18N
        jMnuProdutos.setMnemonic('p');
        jMnuProdutos.setText("Produtos");
        jMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuProdutos);

        jMnuSair1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/saair.JPG"))); // NOI18N
        jMnuSair1.setMnemonic('s');
        jMnuSair1.setText("Sair");
        jMnuSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSair1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuSair1);

        jMenuBar1.add(jMenu1);
        jMenu1.getAccessibleContext().setAccessibleDescription("");

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/movimento.JPG"))); // NOI18N
        jMenu2.setMnemonic('m');
        jMenu2.setText("Movimentos");

        jMnuUsuarios1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/glitter_1490220.png"))); // NOI18N
        jMnuUsuarios1.setMnemonic('v');
        jMnuUsuarios1.setText("Venda");
        jMnuUsuarios1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMnuUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarios1ActionPerformed(evt);
            }
        });
        jMnuUsuarios1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMnuUsuarios1KeyPressed(evt);
            }
        });
        jMenu2.add(jMnuUsuarios1);

        jMenuBar1.add(jMenu2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/necromancer.png"))); // NOI18N
        jMenu5.setMnemonic('m');
        jMenu5.setText("Consultas");

        jMnuUsuarios2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/ram.png"))); // NOI18N
        jMnuUsuarios2.setMnemonic('v');
        jMnuUsuarios2.setText("Consultas Produtos");
        jMnuUsuarios2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMnuUsuarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarios2ActionPerformed(evt);
            }
        });
        jMnuUsuarios2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMnuUsuarios2KeyPressed(evt);
            }
        });
        jMenu5.add(jMnuUsuarios2);

        jMnuUsuarios3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/livre-de-magie.png"))); // NOI18N
        jMnuUsuarios3.setMnemonic('v');
        jMnuUsuarios3.setText("Consultas Usuários");
        jMnuUsuarios3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMnuUsuarios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarios3ActionPerformed(evt);
            }
        });
        jMnuUsuarios3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMnuUsuarios3KeyPressed(evt);
            }
        });
        jMenu5.add(jMnuUsuarios3);

        jMnuUsuarios4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/chapeau-de-sorciere.png"))); // NOI18N
        jMnuUsuarios4.setMnemonic('v');
        jMnuUsuarios4.setText("Consultas Clientes");
        jMnuUsuarios4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMnuUsuarios4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarios4ActionPerformed(evt);
            }
        });
        jMnuUsuarios4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMnuUsuarios4KeyPressed(evt);
            }
        });
        jMenu5.add(jMnuUsuarios4);

        jMnuUsuarios5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/la-magie.png"))); // NOI18N
        jMnuUsuarios5.setMnemonic('v');
        jMnuUsuarios5.setText("Consultas Vendas");
        jMnuUsuarios5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMnuUsuarios5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarios5ActionPerformed(evt);
            }
        });
        jMnuUsuarios5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMnuUsuarios5KeyPressed(evt);
            }
        });
        jMenu5.add(jMnuUsuarios5);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientesActionPerformed
        JDlgCliente telaCliente = new JDlgCliente(this, true);
        telaCliente.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMnuClientesActionPerformed

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
        JDlgUsuarios telaUsuarios = new JDlgUsuarios(this, true);
        telaUsuarios.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void jMnuUsuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMnuUsuariosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuUsuariosKeyPressed

    private void jMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutosActionPerformed
        JDlgProdutos telaProdutos = new JDlgProdutos(this, true);
        telaProdutos.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuProdutosActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JDlgFuncionarios telaFuncionarios = new JDlgFuncionarios(this, true);
        telaFuncionarios.setVisible(true);        // TO        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMnuSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSair1ActionPerformed
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_jMnuSair1ActionPerformed

    private void jMnuUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarios1ActionPerformed
        JDlgVendas telaVenda = new JDlgVendas(this, true);
        telaVenda.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jMnuUsuarios1ActionPerformed

    private void jMnuUsuarios1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMnuUsuarios1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuUsuarios1KeyPressed

    private void jMnuUsuarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarios2ActionPerformed
        JDlgConsultaProdutos telaConsulta = new JDlgConsultaProdutos(this, true);
        telaConsulta.setVisible(true);                 // TODO add your handling code here:
    }//GEN-LAST:event_jMnuUsuarios2ActionPerformed

    private void jMnuUsuarios2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMnuUsuarios2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuUsuarios2KeyPressed

    private void jMnuUsuarios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarios3ActionPerformed
        JDlgConsultaUsuarios telaConsulta = new JDlgConsultaUsuarios(this, true);
        telaConsulta.setVisible(true);                // TODO add your handling code here:
    }//GEN-LAST:event_jMnuUsuarios3ActionPerformed

    private void jMnuUsuarios3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMnuUsuarios3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuUsuarios3KeyPressed

    private void jMnuUsuarios4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarios4ActionPerformed
        JDlgConsultaClientes telaConsulta = new JDlgConsultaClientes(this, true);
        telaConsulta.setVisible(true);                  // TODO add your handling code here:
    }//GEN-LAST:event_jMnuUsuarios4ActionPerformed

    private void jMnuUsuarios4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMnuUsuarios4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuUsuarios4KeyPressed

    private void jMnuUsuarios5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarios5ActionPerformed
        JDlgConsultaVenda telaConsulta = new JDlgConsultaVenda(this, true);
        telaConsulta.setVisible(true);                  // TODO add your handling code here:
    }//GEN-LAST:event_jMnuUsuarios5ActionPerformed

    private void jMnuUsuarios5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMnuUsuarios5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuUsuarios5KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JDlgProdutos telaConsulta = new JDlgProdutos(this, true);
        telaConsulta.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JDlgUsuarios telaUsuarios = new JDlgUsuarios(this, true);
        telaUsuarios.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JDlgCliente telaConsulta = new JDlgCliente(this, true);
        telaConsulta.setVisible(true);                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JDlgConsultaUsuarios telaUsuarios = new JDlgConsultaUsuarios(this, true);
        telaUsuarios.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JDlgConsultaProdutos telaProdutos = new JDlgConsultaProdutos(this, true);
        telaProdutos.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMnuClientes;
    private javax.swing.JMenuItem jMnuProdutos;
    private javax.swing.JMenuItem jMnuSair1;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JMenuItem jMnuUsuarios1;
    private javax.swing.JMenuItem jMnuUsuarios2;
    private javax.swing.JMenuItem jMnuUsuarios3;
    private javax.swing.JMenuItem jMnuUsuarios4;
    private javax.swing.JMenuItem jMnuUsuarios5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
