package bean;
// Generated 28 sept. 2025 19:57:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GdcbFuncionario generated by hbm2java
 */
@Entity
@Table(name="gdcb_funcionario"
    ,catalog="dominique"
)
public class GdcbFuncionario  implements java.io.Serializable {


     private int gdcbIdfuncionario;
     private String gdcbNomeFuncionario;
     private String gdcbCpfFuncionario;
     private String gdcbClt;
     private Date gdcbDataNascimentoFuncionario;
     private String gdcbAtivo;
     private String gdcbEmailFuncionario;
     private String gdcbCargo;
   

    public GdcbFuncionario() {
    }

	
    public GdcbFuncionario(int gdcbIdfuncionario, String gdcbNomeFuncionario, String gdcbCpfFuncionario, String gdcbClt, Date gdcbDataNascimentoFuncionario, String gdcbAtivo, String gdcbEmailFuncionario, String gdcbCargo) {
        this.gdcbIdfuncionario = gdcbIdfuncionario;
        this.gdcbNomeFuncionario = gdcbNomeFuncionario;
        this.gdcbCpfFuncionario = gdcbCpfFuncionario;
        this.gdcbClt = gdcbClt;
        this.gdcbDataNascimentoFuncionario = gdcbDataNascimentoFuncionario;
        this.gdcbAtivo = gdcbAtivo;
        this.gdcbEmailFuncionario = gdcbEmailFuncionario;
        this.gdcbCargo = gdcbCargo;
    }
    public GdcbFuncionario(int gdcbIdfuncionario, String gdcbNomeFuncionario, String gdcbCpfFuncionario, String gdcbClt, Date gdcbDataNascimentoFuncionario, String gdcbAtivo, String gdcbEmailFuncionario, String gdcbCargo, Set gdcbVendas) {
       this.gdcbIdfuncionario = gdcbIdfuncionario;
       this.gdcbNomeFuncionario = gdcbNomeFuncionario;
       this.gdcbCpfFuncionario = gdcbCpfFuncionario;
       this.gdcbClt = gdcbClt;
       this.gdcbDataNascimentoFuncionario = gdcbDataNascimentoFuncionario;
       this.gdcbAtivo = gdcbAtivo;
       this.gdcbEmailFuncionario = gdcbEmailFuncionario;
       this.gdcbCargo = gdcbCargo;
    }
   
     @Id 

    
    @Column(name="gdcb_idfuncionario", unique=true, nullable=false)
    public int getGdcbIdfuncionario() {
        return this.gdcbIdfuncionario;
    }
    
    public void setGdcbIdfuncionario(int gdcbIdfuncionario) {
        this.gdcbIdfuncionario = gdcbIdfuncionario;
    }

    
    @Column(name="gdcb_nomeFuncionario", nullable=false, length=50)
    public String getGdcbNomeFuncionario() {
        return this.gdcbNomeFuncionario;
    }
    
    public void setGdcbNomeFuncionario(String gdcbNomeFuncionario) {
        this.gdcbNomeFuncionario = gdcbNomeFuncionario;
    }

    
    @Column(name="gdcb_cpfFuncionario", nullable=false, length=14)
    public String getGdcbCpfFuncionario() {
        return this.gdcbCpfFuncionario;
    }
    
    public void setGdcbCpfFuncionario(String gdcbCpfFuncionario) {
        this.gdcbCpfFuncionario = gdcbCpfFuncionario;
    }

    
    @Column(name="gdcb_clt", nullable=false, length=1)
    public String getGdcbClt() {
        return this.gdcbClt;
    }
    
    public void setGdcbClt(String gdcbClt) {
        this.gdcbClt = gdcbClt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gdcb_dataNascimentoFuncionario", nullable=false, length=10)
    public Date getGdcbDataNascimentoFuncionario() {
        return this.gdcbDataNascimentoFuncionario;
    }
    
    public void setGdcbDataNascimentoFuncionario(Date gdcbDataNascimentoFuncionario) {
        this.gdcbDataNascimentoFuncionario = gdcbDataNascimentoFuncionario;
    }

    
    @Column(name="gdcb_ativo", nullable=false, length=1)
    public String getGdcbAtivo() {
        return this.gdcbAtivo;
    }
    
    public void setGdcbAtivo(String gdcbAtivo) {
        this.gdcbAtivo = gdcbAtivo;
    }

    
    @Column(name="gdcb_emailFuncionario", nullable=false, length=80)
    public String getGdcbEmailFuncionario() {
        return this.gdcbEmailFuncionario;
    }
    
    public void setGdcbEmailFuncionario(String gdcbEmailFuncionario) {
        this.gdcbEmailFuncionario = gdcbEmailFuncionario;
    }

    
    @Column(name="gdcb_cargo", nullable=false, length=30)
    public String getGdcbCargo() {
        return this.gdcbCargo;
    }
    
    public void setGdcbCargo(String gdcbCargo) {
        this.gdcbCargo = gdcbCargo;
    }

}


