package bean;
// Generated 28 sept. 2025 19:57:38 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GdcbVenda generated by hbm2java
 */
@Entity
@Table(name="gdcb_venda"
    ,catalog="dominique"
)
public class GdcbVenda  implements java.io.Serializable {


     private Integer gdcbIdVenda;
     private GdcbCliente gdcbCliente;
     private GdcbFuncionario gdcbFuncionario;
     private Date gdcbDataVenda;
     private BigDecimal gdcbValorTotal;
     private String gdcbPeriodoVenda;
     private String gdcbAvaliacaoCliente;
     private char gdcbAtivo;
   

    public GdcbVenda() {
    }

	
    public GdcbVenda(GdcbCliente gdcbCliente, GdcbFuncionario gdcbFuncionario, Date gdcbDataVenda, BigDecimal gdcbValorTotal, String gdcbPeriodoVenda, char gdcbAtivo) {
        this.gdcbCliente = gdcbCliente;
        this.gdcbFuncionario = gdcbFuncionario;
        this.gdcbDataVenda = gdcbDataVenda;
        this.gdcbValorTotal = gdcbValorTotal;
        this.gdcbPeriodoVenda = gdcbPeriodoVenda;
        this.gdcbAtivo = gdcbAtivo;
    }
    public GdcbVenda(GdcbCliente gdcbCliente, GdcbFuncionario gdcbFuncionario, Date gdcbDataVenda, BigDecimal gdcbValorTotal, String gdcbPeriodoVenda, String gdcbAvaliacaoCliente, char gdcbAtivo, Set gdcbVendasProdutoses) {
       this.gdcbCliente = gdcbCliente;
       this.gdcbFuncionario = gdcbFuncionario;
       this.gdcbDataVenda = gdcbDataVenda;
       this.gdcbValorTotal = gdcbValorTotal;
       this.gdcbPeriodoVenda = gdcbPeriodoVenda;
       this.gdcbAvaliacaoCliente = gdcbAvaliacaoCliente;
       this.gdcbAtivo = gdcbAtivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="gdcb_idVenda", unique=true, nullable=false)
    public Integer getGdcbIdVenda() {
        return this.gdcbIdVenda;
    }
    
    public void setGdcbIdVenda(Integer gdcbIdVenda) {
        this.gdcbIdVenda = gdcbIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gdcb_idCliente", nullable=false)
    public GdcbCliente getGdcbCliente() {
        return this.gdcbCliente;
    }
    
    public void setGdcbCliente(GdcbCliente gdcbCliente) {
        this.gdcbCliente = gdcbCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gdcb_idFuncionario", nullable=false)
    public GdcbFuncionario getGdcbFuncionario() {
        return this.gdcbFuncionario;
    }
    
    public void setGdcbFuncionario(GdcbFuncionario gdcbFuncionario) {
        this.gdcbFuncionario = gdcbFuncionario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="gdcb_dataVenda", nullable=false, length=19)
    public Date getGdcbDataVenda() {
        return this.gdcbDataVenda;
    }
    
    public void setGdcbDataVenda(Date gdcbDataVenda) {
        this.gdcbDataVenda = gdcbDataVenda;
    }

    
    @Column(name="gdcb_valorTotal", nullable=false, precision=10)
    public BigDecimal getGdcbValorTotal() {
        return this.gdcbValorTotal;
    }
    
    public void setGdcbValorTotal(BigDecimal gdcbValorTotal) {
        this.gdcbValorTotal = gdcbValorTotal;
    }

    
    @Column(name="gdcb_periodoVenda", nullable=false, length=10)
    public String getGdcbPeriodoVenda() {
        return this.gdcbPeriodoVenda;
    }
    
    public void setGdcbPeriodoVenda(String gdcbPeriodoVenda) {
        this.gdcbPeriodoVenda = gdcbPeriodoVenda;
    }

    
    @Column(name="gdcb_avaliacaoCliente", length=100)
    public String getGdcbAvaliacaoCliente() {
        return this.gdcbAvaliacaoCliente;
    }
    
    public void setGdcbAvaliacaoCliente(String gdcbAvaliacaoCliente) {
        this.gdcbAvaliacaoCliente = gdcbAvaliacaoCliente;
    }

    
    @Column(name="gdcb_ativo", nullable=false, length=1)
    public char getGdcbAtivo() {
        return this.gdcbAtivo;
    }
    
    public void setGdcbAtivo(char gdcbAtivo) {
        this.gdcbAtivo = gdcbAtivo;
    }

}


