package bean;
// Generated 19 nov. 2025 22:41:02 by Hibernate Tools 4.3.1


import java.lang.Double;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GdcbProdutos generated by hbm2java
 */
@Entity
@Table(name="gdcb_produtos"
    ,catalog="dominique"
)
public class GdcbProdutos  implements java.io.Serializable {


     private int gdcbIdprodutos;
     private String gdcbNomeProduto;
     private String gdcbMarca;
     private String gdcbPopularidade;
     private String gdcbTipo;
     private String gdcbClassificacaoIdade;
     private Double gdcbPreco;
     private String gdcbAutor;

    public GdcbProdutos() {
    }

	
    public GdcbProdutos(int gdcbIdprodutos, String gdcbNomeProduto, String gdcbMarca, String gdcbPopularidade, String gdcbTipo, Double gdcbPreco, String gdcbAutor) {
        this.gdcbIdprodutos = gdcbIdprodutos;
        this.gdcbNomeProduto = gdcbNomeProduto;
        this.gdcbMarca = gdcbMarca;
        this.gdcbPopularidade = gdcbPopularidade;
        this.gdcbTipo = gdcbTipo;
        this.gdcbPreco = gdcbPreco;
        this.gdcbAutor = gdcbAutor;
    }
    public GdcbProdutos(int gdcbIdprodutos, String gdcbNomeProduto, String gdcbMarca, String gdcbPopularidade, String gdcbTipo, String gdcbClassificacaoIdade, Double gdcbPreco, String gdcbAutor, Set gdcbVendasProdutoses) {
       this.gdcbIdprodutos = gdcbIdprodutos;
       this.gdcbNomeProduto = gdcbNomeProduto;
       this.gdcbMarca = gdcbMarca;
       this.gdcbPopularidade = gdcbPopularidade;
       this.gdcbTipo = gdcbTipo;
       this.gdcbClassificacaoIdade = gdcbClassificacaoIdade;
       this.gdcbPreco = gdcbPreco;
       this.gdcbAutor = gdcbAutor;
    }
   
     @Id 

    
    @Column(name="gdcb_idprodutos", unique=true, nullable=false)
    public int getGdcbIdprodutos() {
        return this.gdcbIdprodutos;
    }
    
    public void setGdcbIdprodutos(int gdcbIdprodutos) {
        this.gdcbIdprodutos = gdcbIdprodutos;
    }

    
    @Column(name="gdcb_nomeProduto", nullable=false, length=50)
    public String getGdcbNomeProduto() {
        return this.gdcbNomeProduto;
    }
    
    public void setGdcbNomeProduto(String gdcbNomeProduto) {
        this.gdcbNomeProduto = gdcbNomeProduto;
    }

    
    @Column(name="gdcb_marca", nullable=false, length=30)
    public String getGdcbMarca() {
        return this.gdcbMarca;
    }
    
    public void setGdcbMarca(String gdcbMarca) {
        this.gdcbMarca = gdcbMarca;
    }

    
    @Column(name="gdcb_popularidade", nullable=false, length=10)
    public String getGdcbPopularidade() {
        return this.gdcbPopularidade;
    }
    
    public void setGdcbPopularidade(String gdcbPopularidade) {
        this.gdcbPopularidade = gdcbPopularidade;
    }

    
    @Column(name="gdcb_tipo", nullable=false, length=30)
    public String getGdcbTipo() {
        return this.gdcbTipo;
    }
    
    public void setGdcbTipo(String gdcbTipo) {
        this.gdcbTipo = gdcbTipo;
    }

    
    @Column(name="gdcb_classificacaoIdade", length=10)
    public String getGdcbClassificacaoIdade() {
        return this.gdcbClassificacaoIdade;
    }
    
    public void setGdcbClassificacaoIdade(String gdcbClassificacaoIdade) {
        this.gdcbClassificacaoIdade = gdcbClassificacaoIdade;
    }

    
    @Column(name="gdcb_preco", nullable=false, precision=10)
    public Double getGdcbPreco() {
        return this.gdcbPreco;
    }
    
    public void setGdcbPreco(Double gdcbPreco) {
        this.gdcbPreco = gdcbPreco;
    }

    
    @Column(name="gdcb_autor", nullable=false, length=60)
    public String getGdcbAutor() {
        return this.gdcbAutor;
    }
    
    public void setGdcbAutor(String gdcbAutor) {
        this.gdcbAutor = gdcbAutor;
    }

@Override
public String toString() {
    return getGdcbNomeProduto()!= null ? getGdcbNomeProduto() : "";
}

}


