package bean;
// Generated 24/11/2025 14:25:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GdcbCliente generated by hbm2java
 */
@Entity
@Table(name="gdcb_cliente"
    ,catalog="db_giovanna_bernazzolli"
)
public class GdcbCliente  implements java.io.Serializable {


     private int gdcbIdcliente;
     private String gdcbNome;
     private String gdcbCpf;
     private String gdcbRg;
     private String gdcbSexo;
     private Date gdcbDataNascimento;
     private String gdcbEmail;
     private String gdcbCep;
     private int gdcbNumeroCasa;
     private String gdcbBairro;
     private String gdcbNomeRua;
     private String gdcbCidade;
     private String gdcbNumeroCelular;
     private String gdcbEscolaridade;
     private String gdcbCursoAtual;
     private String gdcbAtivo;
  
    public GdcbCliente() {
    }

	
    public GdcbCliente(int gdcbIdcliente, String gdcbNome, String gdcbCpf, String gdcbRg, String gdcbSexo, String gdcbEmail, String gdcbCep, int gdcbNumeroCasa, String gdcbBairro, String gdcbNomeRua, String gdcbCidade, String gdcbNumeroCelular, String gdcbEscolaridade, String gdcbCursoAtual) {
        this.gdcbIdcliente = gdcbIdcliente;
        this.gdcbNome = gdcbNome;
        this.gdcbCpf = gdcbCpf;
        this.gdcbRg = gdcbRg;
        this.gdcbSexo = gdcbSexo;
        this.gdcbEmail = gdcbEmail;
        this.gdcbCep = gdcbCep;
        this.gdcbNumeroCasa = gdcbNumeroCasa;
        this.gdcbBairro = gdcbBairro;
        this.gdcbNomeRua = gdcbNomeRua;
        this.gdcbCidade = gdcbCidade;
        this.gdcbNumeroCelular = gdcbNumeroCelular;
        this.gdcbEscolaridade = gdcbEscolaridade;
        this.gdcbCursoAtual = gdcbCursoAtual;
    }
    public GdcbCliente(int gdcbIdcliente, String gdcbNome, String gdcbCpf, String gdcbRg, String gdcbSexo, Date gdcbDataNascimento, String gdcbEmail, String gdcbCep, int gdcbNumeroCasa, String gdcbBairro, String gdcbNomeRua, String gdcbCidade, String gdcbNumeroCelular, String gdcbEscolaridade, String gdcbCursoAtual, String gdcbAtivo, Set gdcbVendas) {
       this.gdcbIdcliente = gdcbIdcliente;
       this.gdcbNome = gdcbNome;
       this.gdcbCpf = gdcbCpf;
       this.gdcbRg = gdcbRg;
       this.gdcbSexo = gdcbSexo;
       this.gdcbDataNascimento = gdcbDataNascimento;
       this.gdcbEmail = gdcbEmail;
       this.gdcbCep = gdcbCep;
       this.gdcbNumeroCasa = gdcbNumeroCasa;
       this.gdcbBairro = gdcbBairro;
       this.gdcbNomeRua = gdcbNomeRua;
       this.gdcbCidade = gdcbCidade;
       this.gdcbNumeroCelular = gdcbNumeroCelular;
       this.gdcbEscolaridade = gdcbEscolaridade;
       this.gdcbCursoAtual = gdcbCursoAtual;
       this.gdcbAtivo = gdcbAtivo;
      
    }
   
     @Id 

    
    @Column(name="gdcb_idcliente", unique=true, nullable=false)
    public int getGdcbIdcliente() {
        return this.gdcbIdcliente;
    }
    
    public void setGdcbIdcliente(int gdcbIdcliente) {
        this.gdcbIdcliente = gdcbIdcliente;
    }

    
    @Column(name="gdcb_nome", nullable=false, length=50)
    public String getGdcbNome() {
        return this.gdcbNome;
    }
    
    public void setGdcbNome(String gdcbNome) {
        this.gdcbNome = gdcbNome;
    }

    
    @Column(name="gdcb_cpf", nullable=false, length=16)
    public String getGdcbCpf() {
        return this.gdcbCpf;
    }
    
    public void setGdcbCpf(String gdcbCpf) {
        this.gdcbCpf = gdcbCpf;
    }

    
    @Column(name="gdcb_rg", nullable=false, length=11)
    public String getGdcbRg() {
        return this.gdcbRg;
    }
    
    public void setGdcbRg(String gdcbRg) {
        this.gdcbRg = gdcbRg;
    }

    
    @Column(name="gdcb_sexo", nullable=false, length=1)
    public String getGdcbSexo() {
        return this.gdcbSexo;
    }
    
    public void setGdcbSexo(String gdcbSexo) {
        this.gdcbSexo = gdcbSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gdcb_dataNascimento", length=10)
    public Date getGdcbDataNascimento() {
        return this.gdcbDataNascimento;
    }
    
    public void setGdcbDataNascimento(Date gdcbDataNascimento) {
        this.gdcbDataNascimento = gdcbDataNascimento;
    }

    
    @Column(name="gdcb_email", nullable=false, length=85)
    public String getGdcbEmail() {
        return this.gdcbEmail;
    }
    
    public void setGdcbEmail(String gdcbEmail) {
        this.gdcbEmail = gdcbEmail;
    }

    
    @Column(name="gdcb_cep", nullable=false, length=14)
    public String getGdcbCep() {
        return this.gdcbCep;
    }
    
    public void setGdcbCep(String gdcbCep) {
        this.gdcbCep = gdcbCep;
    }

    
    @Column(name="gdcb_numeroCasa", nullable=false)
    public int getGdcbNumeroCasa() {
        return this.gdcbNumeroCasa;
    }
    
    public void setGdcbNumeroCasa(int gdcbNumeroCasa) {
        this.gdcbNumeroCasa = gdcbNumeroCasa;
    }

    
    @Column(name="gdcb_bairro", nullable=false, length=45)
    public String getGdcbBairro() {
        return this.gdcbBairro;
    }
    
    public void setGdcbBairro(String gdcbBairro) {
        this.gdcbBairro = gdcbBairro;
    }

    
    @Column(name="gdcb_nomeRua", nullable=false, length=50)
    public String getGdcbNomeRua() {
        return this.gdcbNomeRua;
    }
    
    public void setGdcbNomeRua(String gdcbNomeRua) {
        this.gdcbNomeRua = gdcbNomeRua;
    }

    
    @Column(name="gdcb_cidade", nullable=false, length=45)
    public String getGdcbCidade() {
        return this.gdcbCidade;
    }
    
    public void setGdcbCidade(String gdcbCidade) {
        this.gdcbCidade = gdcbCidade;
    }

    
    @Column(name="gdcb_numeroCelular", nullable=false, length=12)
    public String getGdcbNumeroCelular() {
        return this.gdcbNumeroCelular;
    }
    
    public void setGdcbNumeroCelular(String gdcbNumeroCelular) {
        this.gdcbNumeroCelular = gdcbNumeroCelular;
    }

    
    @Column(name="gdcb_escolaridade", nullable=false, length=60)
    public String getGdcbEscolaridade() {
        return this.gdcbEscolaridade;
    }
    
    public void setGdcbEscolaridade(String gdcbEscolaridade) {
        this.gdcbEscolaridade = gdcbEscolaridade;
    }

    
    @Column(name="gdcb_cursoAtual", nullable=false, length=50)
    public String getGdcbCursoAtual() {
        return this.gdcbCursoAtual;
    }
    
    public void setGdcbCursoAtual(String gdcbCursoAtual) {
        this.gdcbCursoAtual = gdcbCursoAtual;
    }

    
    @Column(name="gdcb_ativo", length=1)
    public String getGdcbAtivo() {
        return this.gdcbAtivo;
    }
    
    public void setGdcbAtivo(String gdcbAtivo) {
        this.gdcbAtivo = gdcbAtivo;
    }


@Override
public String toString() {
    return getGdcbNome() != null ? getGdcbNome() : "";
}

}

