package bean;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GdcbVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="gdcb_venda"
    ,catalog="dominique"
)
public class GdcbVenda  implements java.io.Serializable {

     private Integer gdcbIdItemVenda;
     private GdcbVenda gdcbVenda;
     private GdcbProdutos gdcbProdutos;
     private Integer gdcbQuantidade;
     private BigDecimal gdcbValorUnitario;
     private BigDecimal gdcbDesconto;
     private BigDecimal gdcbValorTotal;

    public GdcbVenda() {
    }

    public GdcbVenda(GdcbVenda gdcbVenda, GdcbProdutos gdcbProdutos, Integer gdcbQuantidade, BigDecimal gdcbValorUnitario, BigDecimal gdcbDesconto, BigDecimal gdcbValorTotal) {
        this.gdcbVenda = gdcbVenda;
        this.gdcbProdutos = gdcbProdutos;
        this.gdcbQuantidade = gdcbQuantidade;
        this.gdcbValorUnitario = gdcbValorUnitario;
        this.gdcbDesconto = gdcbDesconto;
        this.gdcbValorTotal = gdcbValorTotal;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="gdcb_idItemVenda", unique=true, nullable=false)
    public Integer getGdcbIdItemVenda() {
        return this.gdcbIdItemVenda;
    }
    
    public void setGdcbIdItemVenda(Integer gdcbIdItemVenda) {
        this.gdcbIdItemVenda = gdcbIdItemVenda;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gdcb_idVenda", nullable=false)
    public GdcbVenda getGdcbVenda() {
        return this.gdcbVenda;
    }
    
    public void setGdcbVenda(GdcbVenda gdcbVenda) {
        this.gdcbVenda = gdcbVenda;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gdcb_idProduto", nullable=false)
    public GdcbProdutos getGdcbProdutos() {
        return this.gdcbProdutos;
    }
    
    public void setGdcbProdutos(GdcbProdutos gdcbProdutos) {
        this.gdcbProdutos = gdcbProdutos;
    }

    @Column(name="gdcb_quantidade", nullable=false)
    public Integer getGdcbQuantidade() {
        return this.gdcbQuantidade;
    }
    
    public void setGdcbQuantidade(Integer gdcbQuantidade) {
        this.gdcbQuantidade = gdcbQuantidade;
    }

    @Column(name="gdcb_valorUnitario", nullable=false, precision=10, scale=2)
    public BigDecimal getGdcbValorUnitario() {
        return this.gdcbValorUnitario;
    }
    
    public void setGdcbValorUnitario(BigDecimal gdcbValorUnitario) {
        this.gdcbValorUnitario = gdcbValorUnitario;
    }

    @Column(name="gdcb_desconto", nullable=false, precision=5, scale=2)
    public BigDecimal getGdcbDesconto() {
        return this.gdcbDesconto;
    }
    
    public void setGdcbDesconto(BigDecimal gdcbDesconto) {
        this.gdcbDesconto = gdcbDesconto;
    }

    @Column(name="gdcb_valorTotal", nullable=false, precision=10, scale=2)
    public BigDecimal getGdcbValorTotal() {
        return this.gdcbValorTotal;
    }
    
    public void setGdcbValorTotal(BigDecimal gdcbValorTotal) {
        this.gdcbValorTotal = gdcbValorTotal;
    }
}