package bean;
// Generated 24/11/2025 14:25:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GdcbUsuarios generated by hbm2java
 */
@Entity
@Table(name="gdcb_usuarios"
    ,catalog="db_giovanna_bernazzolli"
)
public class GdcbUsuarios  implements java.io.Serializable {


     private int gdcbIdusuarios;
     private String gdcbNome;
     private String gdcbApelido;
     private String gdcbCpf;
     private Date gdcbDataNascimento;
     private String gdcbSenha;
     private int gdcbNivel;
     private String gdcbAtivo;

    public GdcbUsuarios() {
    }

	
    public GdcbUsuarios(int gdcbIdusuarios, String gdcbNome, String gdcbApelido, String gdcbCpf, String gdcbSenha, int gdcbNivel, String gdcbAtivo) {
        this.gdcbIdusuarios = gdcbIdusuarios;
        this.gdcbNome = gdcbNome;
        this.gdcbApelido = gdcbApelido;
        this.gdcbCpf = gdcbCpf;
        this.gdcbSenha = gdcbSenha;
        this.gdcbNivel = gdcbNivel;
        this.gdcbAtivo = gdcbAtivo;
    }
    public GdcbUsuarios(int gdcbIdusuarios, String gdcbNome, String gdcbApelido, String gdcbCpf, Date gdcbDataNascimento, String gdcbSenha, int gdcbNivel, String gdcbAtivo) {
       this.gdcbIdusuarios = gdcbIdusuarios;
       this.gdcbNome = gdcbNome;
       this.gdcbApelido = gdcbApelido;
       this.gdcbCpf = gdcbCpf;
       this.gdcbDataNascimento = gdcbDataNascimento;
       this.gdcbSenha = gdcbSenha;
       this.gdcbNivel = gdcbNivel;
       this.gdcbAtivo = gdcbAtivo;
    }
   
     @Id 

    
    @Column(name="gdcb_idusuarios", unique=true, nullable=false)
    public int getGdcbIdusuarios() {
        return this.gdcbIdusuarios;
    }
    
    public void setGdcbIdusuarios(int gdcbIdusuarios) {
        this.gdcbIdusuarios = gdcbIdusuarios;
    }

    
    @Column(name="gdcb_nome", nullable=false, length=50)
    public String getGdcbNome() {
        return this.gdcbNome;
    }
    
    public void setGdcbNome(String gdcbNome) {
        this.gdcbNome = gdcbNome;
    }

    
    @Column(name="gdcb_apelido", nullable=false, length=25)
    public String getGdcbApelido() {
        return this.gdcbApelido;
    }
    
    public void setGdcbApelido(String gdcbApelido) {
        this.gdcbApelido = gdcbApelido;
    }

    
    @Column(name="gdcb_cpf", nullable=false, length=14)
    public String getGdcbCpf() {
        return this.gdcbCpf;
    }
    
    public void setGdcbCpf(String gdcbCpf) {
        this.gdcbCpf = gdcbCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gdcb_dataNascimento", length=10)
    public Date getGdcbDataNascimento() {
        return this.gdcbDataNascimento;
    }
    
    public void setGdcbDataNascimento(Date gdcbDataNascimento) {
        this.gdcbDataNascimento = gdcbDataNascimento;
    }

    
    @Column(name="gdcb_senha", nullable=false, length=15)
    public String getGdcbSenha() {
        return this.gdcbSenha;
    }
    
    public void setGdcbSenha(String gdcbSenha) {
        this.gdcbSenha = gdcbSenha;
    }

    
    @Column(name="gdcb_nivel", nullable=false)
    public int getGdcbNivel() {
        return this.gdcbNivel;
    }
    
    public void setGdcbNivel(int gdcbNivel) {
        this.gdcbNivel = gdcbNivel;
    }

    
    @Column(name="gdcb_ativo", nullable=false, length=1)
    public String getGdcbAtivo() {
        return this.gdcbAtivo;
    }
    
    public void setGdcbAtivo(String gdcbAtivo) {
        this.gdcbAtivo = gdcbAtivo;
    }




}


